### ISSUE TITLE
Adding QScintilla2 for both Qt4 and Qt5

### ISSUE THREAD

**Issue by dschreij** [conda-forge/qscintilla2-feedstock#4]
I think this is a question for @conda-forge/core. Currently, QScintilla2 is only available for Qt4, but it is possible to compile the same source for Qt5 (in fact is you do so, the only difference is that the Python module is placed in the PyQt5 folder in Python's site-packages, instead of PyQt4. There are no further differences, as far as I can tell, but I can't find any references to confirm this). The current version of Qscintilla2 is pinned on Qt 4.8.*, but I think it is also useful/desirable to add a version of this module that works with Qt5.

What is the best way to go at this; is there a naming convention for multiple versions of the same package that just have different dependencies? I am thinking along the lines of adding -qt4 for the Qt4 package (so it becomes `qscintilla2-qt4`) and let Qt5 have the `qscintilla2` name. I think I have read a discussion where this was suggested, but I can't remember where.

Do you have any thoughts or suggestions on this?

**Comment by scopatz** [comment]
Hi @dschreij - The website claims it is supported on Qt5 as well.  See https://www.riverbankcomputing.com/software/qscintilla/intro

Also, I think if you use conda build features with versions hard-coded, you could have both use the qscintilla2.

Also also, it is probably worth noting that it doesn't look like we have a conda-forge package for Qt5. So this would probably have to wait for that.

**Comment by dschreij** [comment]
Hi @scopatz. It indeed supports Qt5, and the conda build script I wrote uses `qmake -v` of the Qt package that is available in the current environment to determine for which Qt version QScintilla2 needs to be built, so recipe-wise we're ready to go. (It worked at least when building with qt5 from the qt-test channel)

> Also, I think if you use conda build features with versions hard-coded, you could have both use the qscintilla2.

That is an interesting feature/suggestion. So if I would release an identical recipe with differently hardcoded versions, they could exist alongside eachother? This probably isn't possible from the same feedstock, I suppose?

> Also also, it is probably worth noting that it doesn't look like we have a conda-forge package for Qt5. So this would probably have to wait for that.

Alright, I didn't know that conda-forge can't use packages that are in the default channels! Then indeed this is something that needs to wait until Qt5 becomes available on conda-forge.

**Comment by scopatz** [comment]
> That is an interesting feature/suggestion. So if I would release an identical recipe with differently hardcoded versions, they could exist alongside eachother? This probably isn't possible from the same feedstock, I suppose?

That is probably right. It might need to be a different feedstock.

> Alright, I didn't know that conda-forge can't use packages that are in the default channels! Then indeed this is something that needs to wait until Qt5 becomes available on conda-forge.

Oh, conda-forge can use things on the default channel. But qt5 doesn't seem to be on defaults either.  So we probably have to have a qt5 package first is all :)

**Comment by dschreij** [comment]
It is! At least a conda search shows that 5.6.2 is already available.
~~~
conda search qt
...
pyqt                         4.10.4                   py26_0  defaults        
                             4.10.4                   py27_0  defaults        
                             4.10.4                   py33_0  defaults        
                             4.10.4                   py34_0  defaults        
                             4.11.3                   py26_0  defaults        
                             4.11.3                   py27_0  defaults        
                             4.11.3                   py33_0  defaults        
                             4.11.3                   py34_0  defaults        
                             4.11.3                   py35_0  defaults        
                             4.11.4                   py27_0  defaults        
                             4.11.4                   py27_0  conda-forge/osx-64 
                             4.11.4                   py34_0  conda-forge/osx-64 
                             4.11.4                   py34_0  defaults        
                             4.11.4                   py35_0  defaults        
                             4.11.4                   py35_0  conda-forge/osx-64 
                             4.11.4                   py27_1  defaults        
                          *  4.11.4                   py27_1  conda-forge/osx-64 
                             4.11.4                   py34_1  defaults        
                             4.11.4                   py34_1  conda-forge/osx-64 
                             4.11.4                   py35_1  conda-forge/osx-64 
                             4.11.4                   py35_1  defaults        
                             4.11.4                   py27_2  conda-forge/osx-64 
                             4.11.4                   py27_2  defaults        
                             4.11.4                   py34_2  defaults        
                             4.11.4                   py34_2  conda-forge/osx-64 
                             4.11.4                   py35_2  defaults        
                             4.11.4                   py35_2  conda-forge/osx-64 
                             4.11.4                   py27_3  defaults        
                             4.11.4                   py34_3  defaults        
                             4.11.4                   py35_3  defaults        
                          .  4.11.4                   py27_4  defaults        
                             4.11.4                   py34_4  defaults        
                          .  4.11.4                   py35_4  defaults        
                          .  5.6.0                    py27_0  defaults        
                             5.6.0                    py34_0  defaults        
                             5.6.0                    py35_0  defaults        
                             5.6.0                    py27_1  defaults        
                             5.6.0                    py34_1  defaults        
                             5.6.0                    py35_1  defaults

...
   
qt                           4.7.4                         0  defaults        
                             4.8.5                         2  defaults        
                             4.8.5                         3  defaults        
                             4.8.6                         0  defaults        
                             4.8.6                         2  defaults        
                             4.8.6                         3  defaults        
                             4.8.7                         1  defaults        
                             4.8.7                         2  defaults        
                             4.8.7                         3  defaults        
                          *  4.8.7                         4  defaults        
                          .  5.6.0                         0  defaults        
                             5.6.2                         0  defaults        

...
~~~

I think the confusion is caused by that it is still named qt (and not qt5) so it just snuck in under the radar, and a search for `qt5` doesn't show it.

**Comment by scopatz** [comment]
Oh you are right! My mistake. I would pursue the features route, then, and have a different feedstock for the qt5 version.

**Comment by dschreij** [comment]
Ok, so should I do this with a new PR to staged-recipes and name it differently? I doubt that even though you can have two packages with the same name, but differently pinned versions, you can't have 2 feedstocks with the same name.

**Comment by scopatz** [comment]
My knowledge of where things will start to break isn't perfect here.  Probably best to ask @conda-forge/core

**Comment by dschreij** [comment]
@conda-forge/core Do you have any new insights on this matter? I saw a new version of QScintilla2 had been released, and I hope to create both a Qt4 and 5 compatible update.

**Comment by scopatz** [comment]
I would say that you should start with a separate package name and go from there.
